package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class ContactDeletionTests extends TestBase{


  @Test
  public void testContactDeletion() {
    app.goToHomePage();
    app.deleteContact();
    app.getContactHelper().returnToHomePage();
  }

}
