package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.ContactData;

public class ContactCreationTests extends TestBase {



  @Test
  public void testContactCreation() {
    
    app.goToAddNewContactPage();
    app.getContactHelper().fillContactForm(new ContactData("Alex", "Pro", "AlexPro", "Sovcom", "Saratov", "89061539625", "mail@mail.ru"));
    app.getContactHelper().returnToHomePage();
  }

}
