package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {

    app.goTo().goToGroupPage();
    app.group().initGroupCreation();
    app.group().fillGroupForm(new GroupData("test2", "test3", "test4"));
    app.group().submitGroupCreation();
    app.group().returnToGroupPage();
  }

}
