package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    app.goTo().groupPage();
    int before = app.group().getGroupCount(); // список групп до
    app.group().initGroupCreation();
    app.group().fillGroupForm(new GroupData().withName("test2").withHeader("test3").withFooter("test4"));
    app.group().submitGroupCreation();
    app.group().returnToGroupPage();
    int after = app.group().getGroupCount(); // список групп после
    Assert.assertEquals(after, before + 1); // сравниваем список групп до и после
  }

}
