package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class GroupDeletionTests extends TestBase {

  @BeforeMethod
  public void ensurePreconditions() {
    app.goTo().groupPage();
  }

  @Test
  public void testGroupDeletion() {
    app.group().selectGroup(By.name("selected[]"));
    app.group().deleteSelectedGroups(By.name("delete"));
    app.group().returnToGroupPage();
  }

}
