package ru.stqa.pft.addressbook.test;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class GroupDeletionTests extends TestBase {

  @BeforeMethod
  public void ensurePreconditions() {
    app.goTo().groupPage();
  }

  @Test
  public void testGroupDeletion() {
    int before = app.group().getGroupCount(); // список групп до
    app.group().selectGroup(By.name("selected[]"));
    app.group().deleteSelectedGroups(By.name("delete"));
    app.group().returnToGroupPage();
    int after = app.group().getGroupCount(); // список групп после
    Assert.assertEquals(after, before - 1); // сравниваем список групп до и после
  }

}
